version: '3'
services:
  medscantrack:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 6000:6000
      - 6001:6001
    volumes:
      - /db:/db
      - /scp:/scp